version: '2'

services:
  grimer:
    build: ./source/
    depends_on:
      - db
    ports:
      - 80:80
    volumes:
      - ./source:/var/www/html/
    restart: always
    environment:
      DB_HOST: db
      DB_PASSWORD: password
      DB_NAME: grimer

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql

  composer:
    restart: 'no'
    image: composer:latest
    command: install
    depends_on:
      - grimer
    volumes:
      - ./source:/app

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      ROOT_PASSWORD: password
    ports:
      - 22222:80

volumes:
  db-data:
    driver: local
